### PR TITLE
Bump elixir version to 1.8.1

### PR DESCRIPTION
**Pull request by Ebtoulson**

### CODE REVIEW

**Comment by doomspork** [comment]
Have we tested our apps with this? I found when runnings a few things locally under 1.8 I was greeted by compilation errors. I didn't investigate them at the time because the apps themselves were using an earlier version but it might be worth double checking.

**Comment by Ebtoulson** [comment]
@doomspork I haven't tried 1.8.1 but 1.8 worked fine for me. I figured we wanted to include the bug fixes that were included in the latest.

**Comment by KevinMarth** [comment]
RMS was tested locally with 1.8.1 and seems OK.

**Comment by doomspork** [comment]
Ah! This will just deploy a new tag which shouldn't be an issue since I believe all applications use a specific tag instead of `latest`. I was concerned we could have issues with `latest` changing but that won't matter I think.

**Pull request merged**
