### PR TITLE
Bump Elixir version to 1.7.3

### PR DESCRIPTION
**Pull request by michaelstalker**
[Card](https://github.com/rentpath/mobile_gateway/projects/1#card-13823238)

### CODE REVIEW

**Comment by Stratus3D** [comment]
Do we need to tag another release of rp_elixir now that this is merged?

**Comment by doomspork** [comment]
@Stratus3D https://hub.docker.com/r/rentpath/rp_elixir/tags/

**Comment by Stratus3D** [comment]
I should have said Git tag. I do not see a Git tag on Github for this version.

**Comment by michaelstalker** [comment]
Done 😄 
https://github.com/rentpath/rp_elixir/releases/tag/v1.7.3-alpine-otp-21

**Pull request merged**
